-- MySQL Script generated by MySQL Workbench
-- Mon Oct 12 21:13:16 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `testdb` ;

-- -----------------------------------------------------
-- Table `testdb`.`user_login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`user_login` ;

CREATE TABLE IF NOT EXISTS `testdb`.`user_login` (
  `user_id` INT(70) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_email` VARCHAR(45) NOT NULL COMMENT '',
  `user_password` VARCHAR(45) NULL COMMENT '',
  `user_join_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`user_info` ;

CREATE TABLE IF NOT EXISTS `testdb`.`user_info` (
  `user_info_id` INT(70) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT(70) NOT NULL COMMENT '',
  `user_name` VARCHAR(45) NULL COMMENT '',
  `user_location` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`user_info_id`)  COMMENT '',
  INDEX `fk_user_info_user_login_idx` (`user_id` ASC)  COMMENT '',
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_info_user_login`
    FOREIGN KEY (`user_id`)
    REFERENCES `testdb`.`user_login` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`user_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`user_status` ;

CREATE TABLE IF NOT EXISTS `testdb`.`user_status` (
  `user_status_id` INT(70) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT(70) NOT NULL COMMENT '',
  `status_text` TEXT NULL COMMENT '',
  `status_time` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`user_status_id`)  COMMENT '',
  INDEX `fk_user_status_user_login1_idx` (`user_id` ASC)  COMMENT '',
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_status_user_login1`
    FOREIGN KEY (`user_id`)
    REFERENCES `testdb`.`user_login` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
