-- MySQL Script generated by MySQL Workbench
-- Sat Oct 17 14:29:31 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `testdb` ;

-- -----------------------------------------------------
-- Table `testdb`.`TBL_ING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`TBL_ING` ;

CREATE TABLE IF NOT EXISTS `testdb`.`TBL_ING` (
  `ING_SEQ` INT NOT NULL AUTO_INCREMENT COMMENT 'Secuencia de Ingreso',
  `ID_ING` VARCHAR(20) NOT NULL COMMENT 'ID de Ingreso',
  `ACT_FLG` CHAR(1) NULL DEFAULT '1' COMMENT 'Flag de Actividad',
  `CRT_TIM` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de Creación',
  `UPD_TIM` TIMESTAMP NULL COMMENT 'Fecha de Actualización',
  UNIQUE INDEX `DOC_ING_UNIQUE` (`ID_ING` ASC)  COMMENT '',
  PRIMARY KEY (`ING_SEQ`)  COMMENT '')
ENGINE = InnoDB
COMMENT = 'Tabla de Ingresos';


-- -----------------------------------------------------
-- Table `testdb`.`TBL_SAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`TBL_SAL` ;

CREATE TABLE IF NOT EXISTS `testdb`.`TBL_SAL` (
  `SAL_SEQ` INT NOT NULL AUTO_INCREMENT COMMENT 'Secuencia de Salida',
  `ID_SAL` VARCHAR(20) NOT NULL COMMENT 'ID de Salida',
  `ORD` VARCHAR(20) NULL COMMENT 'Orden',
  `ACT_FLG` CHAR(1) NULL DEFAULT 1 COMMENT 'Flag de Actividad',
  `CRT_TIM` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de Creación',
  `UPD_TIM` TIMESTAMP NULL COMMENT 'Fecha de Actualización',
  PRIMARY KEY (`SAL_SEQ`)  COMMENT '',
  UNIQUE INDEX `DOC_SAL_UNIQUE` (`ID_SAL` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = 'Tabla de Salidas';


-- -----------------------------------------------------
-- Table `testdb`.`TBL_ART`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`TBL_ART` ;

CREATE TABLE IF NOT EXISTS `testdb`.`TBL_ART` (
  `ART_SEQ` INT NOT NULL AUTO_INCREMENT COMMENT 'Secuencia de Artículo',
  `ID_ART` VARCHAR(20) NOT NULL COMMENT 'ID de Artículo',
  `DESC` NVARCHAR(100) NULL COMMENT 'Descripción',
  `CANT_MED` VARCHAR(10) NULL DEFAULT 'Unidad' COMMENT 'Medida de Cantidad',
  `VAL_REP` INT NULL COMMENT 'Valor de Reposición ',
  `PR_UNIT` DECIMAL(10,2) NULL COMMENT 'Precio por Unidad de medida',
  `ACT_FLG` CHAR(1) NULL DEFAULT 1 COMMENT 'Flag de Actividad',
  `CRT_TIM` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de Creación',
  `UPD_TIM` TIMESTAMP NULL COMMENT 'Fecha de Actualización',
  PRIMARY KEY (`ART_SEQ`)  COMMENT '',
  UNIQUE INDEX `ID_ART_UNIQUE` (`ID_ART` ASC)  COMMENT '')
ENGINE = InnoDB
COMMENT = 'Tabla de Artículos';


-- -----------------------------------------------------
-- Table `testdb`.`TBL_ING_DET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`TBL_ING_DET` ;

CREATE TABLE IF NOT EXISTS `testdb`.`TBL_ING_DET` (
  `ING_DET_SEQ` INT NOT NULL AUTO_INCREMENT COMMENT 'Secuencia de Ingreso Detallado',
  `ING_SEQ` INT NOT NULL COMMENT 'Secuencia de Ingreso',
  `ID_ART` VARCHAR(20) NOT NULL COMMENT 'ID de Artículo',
  `ID_ALM` VARCHAR(20) NOT NULL COMMENT 'ID de Almacén',
  `CANT` DECIMAL(10,2) NOT NULL COMMENT 'Cantidad',
  `ACT_FLG` CHAR(1) NULL DEFAULT 1 COMMENT 'Flag de Actividad',
  `CRT_TIM` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de Creación',
  `UPD_TIM` TIMESTAMP NULL COMMENT 'Fecha de Actualización',
  INDEX `fk_TBL_ING_DET_TBL_ING1_idx` (`ING_SEQ` ASC)  COMMENT '',
  PRIMARY KEY (`ING_DET_SEQ`)  COMMENT '',
  INDEX `fk_TBL_ING_DET_TBL_ART1_idx` (`ID_ART` ASC)  COMMENT '',
  CONSTRAINT `fk_TBL_ING_DET_TBL_ING1`
    FOREIGN KEY (`ING_SEQ`)
    REFERENCES `testdb`.`TBL_ING` (`ING_SEQ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_ING_DET_TBL_ART1`
    FOREIGN KEY (`ID_ART`)
    REFERENCES `testdb`.`TBL_ART` (`ID_ART`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabla de Detalles de Ingreso';


-- -----------------------------------------------------
-- Table `testdb`.`TBL_SAL_DET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`TBL_SAL_DET` ;

CREATE TABLE IF NOT EXISTS `testdb`.`TBL_SAL_DET` (
  `SAL_DET_SEQ` INT NOT NULL AUTO_INCREMENT COMMENT 'Secuencia de Salida Detallada',
  `SAL_SEQ` INT NOT NULL COMMENT 'Secuencia de Salida',
  `ID_ART` VARCHAR(20) NOT NULL COMMENT 'ID de Artículo',
  `ID_ALM` VARCHAR(20) NOT NULL COMMENT 'ID de Almacén',
  `CANT` DECIMAL(10,2) NOT NULL COMMENT 'Cantidad',
  `ACT_FLG` CHAR(1) NULL DEFAULT 1 COMMENT 'Flag de Actividad',
  `CRT_TIM` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de Creación',
  `UPD_TIM` TIMESTAMP NULL COMMENT 'Fecha de Actualización',
  PRIMARY KEY (`SAL_DET_SEQ`)  COMMENT '',
  INDEX `fk_TBL_SAL_DET_TBL_ART1_idx` (`ID_ART` ASC)  COMMENT '',
  CONSTRAINT `fk_TBL_SAL_DET_TBL_SAL1`
    FOREIGN KEY (`SAL_SEQ`)
    REFERENCES `testdb`.`TBL_SAL` (`SAL_SEQ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_SAL_DET_TBL_ART1`
    FOREIGN KEY (`ID_ART`)
    REFERENCES `testdb`.`TBL_ART` (`ID_ART`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabla de Detalles de Salida';


-- -----------------------------------------------------
-- Table `testdb`.`TBL_ALM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`TBL_ALM` ;

CREATE TABLE IF NOT EXISTS `testdb`.`TBL_ALM` (
  `ALM_SEQ` INT NOT NULL AUTO_INCREMENT COMMENT 'Secuencia de Almacén',
  `ID_ALM` VARCHAR(20) NOT NULL COMMENT 'ID de Almacén',
  `ACT_FLG` CHAR(1) NULL DEFAULT 1 COMMENT 'Flag de Actividad',
  `CRT_TIM` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de Creación',
  `UPD_TIM` TIMESTAMP NULL COMMENT 'Fecha de Actualización',
  PRIMARY KEY (`ALM_SEQ`)  COMMENT '')
ENGINE = InnoDB
COMMENT = 'Tabla de Almacenes';


-- -----------------------------------------------------
-- Table `testdb`.`TBL_ALM_DET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`TBL_ALM_DET` ;

CREATE TABLE IF NOT EXISTS `testdb`.`TBL_ALM_DET` (
  `ALM_DET_SEQ` INT NOT NULL AUTO_INCREMENT COMMENT 'Secuencia de Almacén Detallado',
  `ALM_SEQ` INT NOT NULL COMMENT 'Secuencia de Almacén',
  `ID_ART` VARCHAR(20) NOT NULL COMMENT 'ID de Artículo',
  `CANT` DECIMAL(10,2) NOT NULL COMMENT 'Cantidad',
  `ACT_FLG` CHAR(1) NULL DEFAULT 1 COMMENT 'Flag de Actividad',
  `CRT_TIM` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de Creación',
  `UPD_TIM` TIMESTAMP NULL COMMENT 'Fecha de Actualización',
  PRIMARY KEY (`ALM_DET_SEQ`)  COMMENT '',
  INDEX `fk_TBL_ALM_DET_TBL_ALM1_idx` (`ALM_SEQ` ASC)  COMMENT '',
  INDEX `fk_TBL_ALM_DET_TBL_ART1_idx` (`ID_ART` ASC)  COMMENT '',
  CONSTRAINT `fk_TBL_ALM_DET_TBL_ALM1`
    FOREIGN KEY (`ALM_SEQ`)
    REFERENCES `testdb`.`TBL_ALM` (`ALM_SEQ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_ALM_DET_TBL_ART1`
    FOREIGN KEY (`ID_ART`)
    REFERENCES `testdb`.`TBL_ART` (`ID_ART`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabla de Detalles de Almacén';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
