USE testdb;
DROP PROCEDURE IF EXISTS SP_INSERT_DETALLE;

DELIMITER $$
CREATE PROCEDURE SP_INSERT_DETALLE (IN query varchar(8000), IN mvmt_type varchar(31), IN mvmt_id int(11))
BEGIN
    DECLARE `_rollback` BOOL DEFAULT 0;
    DECLARE done INT DEFAULT FALSE;

	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET `_rollback` = 1;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
	SET @v = query;
	PREPARE stmt FROM @v;
    START TRANSACTION;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;

    CALL SP_PROCESS_MVMT('ADD', mvmt_type, mvmt_id);
    IF `_rollback` THEN
        ROLLBACK;
    ELSE
        COMMIT;
    END IF;
END$$
DELIMITER ;