USE testdb;
DROP PROCEDURE IF EXISTS SP_PROCESS_DELETE_INGRESO;

DELIMITER $$
CREATE PROCEDURE SP_PROCESS_DELETE_INGRESO (IN id_ingreso int(11))
BEGIN
    DECLARE `_rollback` BOOL DEFAULT 0;
    DECLARE done INT DEFAULT FALSE;

	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET `_rollback` = 1;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

	SET @idIngreso = id_ingreso;
	SET @v = CONCAT('DELETE FROM DETALLE_INGRESO WHERE FK_INGRESO =', @idIngreso);
	PREPARE stmt FROM @v;
    
    START TRANSACTION;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
    IF `_rollback` THEN
        ROLLBACK;
    ELSE
        COMMIT;
    END IF;
END$$
DELIMITER ;